#!/usr/bin/env python3
"""
apply_home_filings.py — home twin of apply_filed_changes.py (auto).

Turns primary-source SERFF HOME rate filings into renormalized drift on the home
tool's relative layer, applied as a SEPARATE HOME_DRIFT layer (not by mutating the
aggregator-calibrated STATE_CARRIER_ADJ). This is the "prior + primary-source
update" design: the aggregator model is the prior; filings drift it; the two
multiply at render time (effective tilt = base × STATE_CARRIER_ADJ × HOME_DRIFT).
As filings accrue post-anchor, the tool gets more primary-sourced — and a re-
calibration resets the drift (bump the anchor) so nothing is ever double-counted.

Math (same discipline as the auto engine):
  F(s,c)   = Π (1 + approved_pct/100) over carrier c's HOME filings whose effective
             date is AFTER the state's home anchor (earlier = already in the
             aggregator snapshot → skipped, no double-count). Entities premium-weighted.
  F̄(s)     = weighted mean of F across the roster carriers with a post-anchor filing
             (weight = SERFF written_premium where present, else equal).
  DRIFT(s,c)= F(s,c) / F̄(s)                     (shifts ORDERING, not level)
  level    = stateAvg(s) × F̄(s), ±10%/yr cap — REPORTED only (not auto-applied).
  GATE     = only drift a state once we've pulled >= HOME_GATE_MIN of its top home
             carriers (coverage, any date); else compute + hold.

Only carriers in the home tool roster (HOME_CARRIERS) can drift — aggregator-blind
regionals (LA Farm Bureau, Allied Trust, Cajun, ...) have no roster base to tilt and
are skipped (they'd need a manual base entry, like the Germania auto fix).

Usage:
  python3 apply_home_filings.py            # dry-run report to stdout
  python3 apply_home_filings.py --emit     # also write home_drift.json (provenance sidecar)
  python3 apply_home_filings.py --apply     # inject the computed HOME_DRIFT block into home/index.html
"""
import json
import re
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent
INDEX = ROOT / "home" / "index.html"
FILINGS = ROOT / "serff_home_filings.json"
ANCHORS = ROOT / "anchor_dates_home.json"
MARKET = ROOT / "home_market_share.json"
OUT = ROOT / "home_drift.json"

DRIFT_BEGIN = "// ── HOME_DRIFT (primary-source renormalized drift) ─ GENERATED by apply_home_filings.py ──"
DRIFT_END = "// ── END HOME_DRIFT ──"

# Home top carriers for the coverage gate (nationals that dominate home + are in the roster).
HOME_TOP = ["State Farm", "Allstate", "USAA", "Farmers", "Liberty Mutual", "Travelers", "Nationwide"]
HOME_GATE_MIN = 3

# serff home carrier family -> HOME_CARRIERS roster key (only where they differ).
ROSTER_ALIAS = {
    "Amica": "Amica Mutual",
    "Hartford": "The Hartford",
    "The Hartford": "The Hartford",
    "Erie": "Erie Insurance",
}


def roster_name(carrier):
    return ROSTER_ALIAS.get(carrier, carrier)


def load_model():
    """Parse the home roster names, STATE_CARRIER_ADJ, and per-state avg from home/index.html."""
    html = INDEX.read_text(encoding="utf-8")
    roster = set(re.findall(r'\{\s*\n\s*name:"([^"]+)"', html))
    if not roster:  # roster objects are on one line in some builds
        roster = set(re.findall(r'name:"([^"]+)",\s*base:', html))
    adj = {}
    block = re.search(r"const STATE_CARRIER_ADJ\s*=\s*\{(.*?)\n\};", html, re.DOTALL)
    if not block:
        sys.exit("could not locate STATE_CARRIER_ADJ in home/index.html")
    for m in re.finditer(r'"([A-Z]{2})":\s*(\{[^}]*\})', block.group(1)):
        adj[m.group(1)] = json.loads(m.group(2))
    stateavg = {}
    for m in re.finditer(r'"([A-Z]{2})":\s*\{[^}]*?\bavg:\s*(\d+(?:\.\d+)?)', html):
        stateavg[m.group(1)] = float(m.group(2))
    if not roster:
        sys.exit("HOME_CARRIERS roster parsed empty — home/index.html format may have changed.")
    return roster, adj, stateavg


def eff_date(row):
    return row.get("effective_new") or row.get("effective_renewal")


def base_tracking(t):
    parts = t.split("-")
    return f"{parts[0]}-{parts[1]}" if len(parts) >= 2 else t


def load_market_share():
    """NAIC homeowners market share by roster name → (weight_fn, floor). Missing file = None."""
    if not MARKET.exists():
        return None
    ms = json.load(open(MARKET))
    natl, states = ms["national"], ms.get("states", {})
    floor = ms["_meta"]["de_minimis_floor"]

    def weight(st, c):
        return states.get(st, {}).get(c) or natl.get(c) or floor
    return weight


def compute(roster, adj, stateavg, filings, anchors, ms_weight=None):
    anchor_default = anchors["default"]
    anchor_state = anchors.get("states", {})

    by_sc = defaultdict(list)
    coverage = defaultdict(set)
    for r in filings:
        if r.get("line") != "home" or r.get("overall_pct") is None:
            continue
        rc = roster_name(r["carrier"])
        by_sc[(r["state"], rc)].append(r)
        coverage[r["state"]].add(rc)

    report = {"_meta": {
        "generated": date.today().isoformat(),
        "purpose": "Renormalized drift on the home tool from SERFF home filings (separate HOME_DRIFT layer, "
                   "applied on top of STATE_CARRIER_ADJ). Provenance keyed by tracking #.",
        "anchor_source": anchors["_meta"]["default_source"],
        "gate_rule": f">= {HOME_GATE_MIN} of {HOME_TOP} covered (any date)",
    }, "states": {}}
    drift_layer = {}

    for st in sorted({s for (s, _) in by_sc}):
        anc = anchor_state.get(st, anchor_default)
        covered = [c for c in HOME_TOP if c in coverage[st]]
        gate_pass = len(covered) >= HOME_GATE_MIN

        carriers, not_in_roster = {}, []
        F_by_c, prem_by_c = {}, {}
        for (s2, rc), rows in by_sc.items():
            if s2 != st:
                continue
            post = [r for r in rows if eff_date(r) and eff_date(r) > anc
                    and r.get("overall_pct") not in (None, 0, 0.0)
                    and not r.get("drift_exclude")]
            if not post:
                continue
            num = den = 0.0
            for r in post:
                wp = r.get("written_premium") or 0
                num += r["overall_pct"] * wp
                den += wp
            wavg = (num / den) if den else sum(r["overall_pct"] for r in post) / len(post)
            F = 1.0 + wavg / 100.0
            entry = {"wavg_pct": round(wavg, 3), "F": round(F, 5), "written_premium": den or None,
                     "trackings": sorted({base_tracking(r["tracking"]) for r in post}),
                     "effective": sorted({eff_date(r) for r in post})}
            if rc in roster:
                F_by_c[rc] = F
                prem_by_c[rc] = den or 0.0
                carriers[rc] = entry
            else:
                entry["carrier"] = rc
                not_in_roster.append(entry)

        # F̄ weight basis (one unit across carriers): SERFF written_premium when ANY participating carrier
        # reports it (the actual book each filing covers); else NAIC homeowners market share (CA/TX rows
        # carry no premium — without a weight F̄ collapses to an equal mean); else equal as a last resort.
        Fbar, weight_basis = None, None
        if F_by_c:
            if any(prem_by_c[c] > 0 for c in F_by_c):
                weights, weight_basis = dict(prem_by_c), "serff_written_premium"
            elif ms_weight:
                weights, weight_basis = {c: ms_weight(st, c) for c in F_by_c}, "naic_home_market_share"
            else:
                weights, weight_basis = {c: 1.0 for c in F_by_c}, "equal"
            wsum = sum(weights.values())
            Fbar = (sum(F_by_c[c] * weights[c] for c in F_by_c) / wsum) if wsum else sum(F_by_c.values()) / len(F_by_c)
            for c, e in carriers.items():
                base_adj = adj.get(st, {}).get(c, 1.0)
                e["adj_base"] = base_adj
                e["drift"] = round(e["F"] / Fbar, 4)
                e["effective_tilt"] = round(base_adj * e["drift"], 4)

        level = None
        if Fbar and st in stateavg:
            capped = max(0.90, min(1.10, Fbar))
            level = {"stateAvg": stateavg[st], "Fbar": round(Fbar, 5),
                     "stateAvg_drifted": round(stateavg[st] * capped, 0), "capped": capped != Fbar}

        if gate_pass and carriers:
            drift_layer[st] = {c: e["drift"] for c, e in carriers.items() if abs(e["drift"] - 1.0) >= 0.0005}

        report["states"][st] = {
            "anchor_as_of": anc, "top_covered": covered, "gate_pass": gate_pass,
            "Fbar": round(Fbar, 5) if Fbar else None, "weight_basis": weight_basis,
            "applied_carriers": carriers if gate_pass else {},
            "held_gate_closed": {} if gate_pass else carriers,
            "filings_not_in_roster": not_in_roster,
            "level_drift": level if gate_pass else None,
        }
    # prune empty states from the applied layer
    drift_layer = {st: d for st, d in drift_layer.items() if d}
    return report, drift_layer


def write_drift_block(drift_layer):
    """Inject the computed HOME_DRIFT object between its markers in home/index.html (idempotent, safe)."""
    html = INDEX.read_text(encoding="utf-8")
    i, j = html.find(DRIFT_BEGIN), html.find(DRIFT_END)
    if i < 0 or j < 0:
        sys.exit("HOME_DRIFT markers not found in home/index.html — cannot apply.")
    # body between the comment header and the END marker: keep the comment, replace the const literal
    head_end = html.index("const HOME_DRIFT", i)
    lines = ["const HOME_DRIFT = {"]
    for st in sorted(drift_layer):
        obj = ", ".join(f'"{c}": {v:g}' for c, v in sorted(drift_layer[st].items()))
        lines.append(f'  "{st}": {{ {obj} }},')
    lines.append("};")
    new = html[:head_end] + "\n".join(lines) + "\n" + html[j:]
    INDEX.write_text(new, encoding="utf-8")


def main():
    if "--help" in sys.argv or "-h" in sys.argv:
        print(__doc__)
        return
    roster, adj, stateavg = load_model()
    filings = json.load(open(FILINGS))["filings"]
    anchors = json.load(open(ANCHORS))
    report, drift_layer = compute(roster, adj, stateavg, filings, anchors, load_market_share())

    print(f"home anchor (default): {anchors['default']}   |   gate: >={HOME_GATE_MIN} top home carriers covered\n")
    for st, s in report["states"].items():
        gate = "GATE PASS" if s["gate_pass"] else "gate CLOSED"
        wb = f"  |  weight {s['weight_basis']}" if s.get("weight_basis") else ""
        print(f"== {st} ==  anchor {s['anchor_as_of']}  |  covered {s['top_covered']}  |  {gate}{wb}")
        applied = s["applied_carriers"] if s["gate_pass"] else s["held_gate_closed"]
        if not applied and not s["filings_not_in_roster"]:
            print("   no post-anchor roster filings — aggregator baseline stands (no drift).\n")
            continue
        for c, e in sorted(applied.items(), key=lambda kv: kv[1]["wavg_pct"]):
            print(f"   {c:16} {e['wavg_pct']:+6.2f}%  drift ×{e['drift']}  "
                  f"(tilt {e['adj_base']}→{e['effective_tilt']})  [{','.join(e['trackings'])}]")
        for e in sorted(s["filings_not_in_roster"], key=lambda x: x["wavg_pct"]):
            print(f"   {e['carrier']:16} {e['wavg_pct']:+6.2f}%  not in home roster (needs a base entry)")
        if s["level_drift"]:
            ld = s["level_drift"]
            print(f"   level: stateAvg {ld['stateAvg']:.0f} → {ld['stateAvg_drifted']:.0f} "
                  f"(F̄={ld['Fbar']}{' capped' if ld['capped'] else ''})  [reported, not applied]")
        print()

    if "--emit" in sys.argv:
        json.dump(report, open(OUT, "w"), indent=1)
        print(f"wrote {OUT.name}")
    if "--apply" in sys.argv:
        write_drift_block(drift_layer)
        n = sum(len(v) for v in drift_layer.values())
        print(f"applied HOME_DRIFT to home/index.html — {len(drift_layer)} state(s), {n} carrier drift(s)")
    if "--emit" not in sys.argv and "--apply" not in sys.argv:
        print("(dry-run; --emit writes home_drift.json, --apply injects HOME_DRIFT into home/index.html)")


if __name__ == "__main__":
    main()
