#!/usr/bin/env python3
"""
gen_product_offsets.py — renters/home carrier-by-state offset pass.

Replicates auto's modeled cost-responsiveness tilt (RATE_METHODOLOGY.md §3) for
the renters and home tools, which previously had NO per-state carrier variation
(every national carrier kept the same relative rank in all 51 states; only the
state average scaled the whole board).

For each national carrier (no `states:` footprint array — regionals already carry
a state-appropriate base, so they are skipped, same rule as auto):

    offset = round( 1 + k * (2*costPercentile - 1), 2 )   # dropped if it rounds to 1.00
    costPercentile = rank of the state's avg, 0 (cheapest) … 1 (priciest)

k = the carrier's relative-price slope vs. state cost. Agent/traditional carriers
load high-cost states (k>0); direct/value carriers hold the line (k<0). Values are
archetype-based and consistent with auto's published k table; modeled/directional,
not citation-exact (verify by confirming the cheap/expensive ordering still holds).

Inserts `const STATE_CARRIER_ADJ = {...}` (between idempotent markers) and patches
estimatePremium to multiply base by the per-state tilt. Safe insert — never
replaces a <script> block (see CLAUDE.md).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# Per-carrier cost-responsiveness slope. Agent/traditional load high-cost states
# (k>0); direct/value hold the line (k<0). Aliases cover renters vs home naming.
K = {
    # agent / traditional — load high-cost states
    "Chubb": 0.12,
    "Allstate": 0.10,
    "Liberty Mutual": 0.09,
    "Farmers": 0.08,
    "Amica": 0.05, "Amica Mutual": 0.05,
    "The Hartford": 0.05,
    "Kemper": 0.05,
    "Safeco": 0.04,
    "State Farm": 0.03,
    # direct / value — hold the line in high-cost states
    "Travelers": -0.07,
    "GEICO": -0.06,
    "Toggle": -0.06,
    "Progressive": -0.05,
    "Nationwide": -0.05,
    "Assurant": -0.05,
    "USAA": -0.04,
}

BEGIN = "// ── STATE_CARRIER_ADJ (per-state carrier tilt) ─ GENERATED by gen_product_offsets.py ──"
END = "// ── END STATE_CARRIER_ADJ ──"

PRODUCTS = {
    "renters": {
        "src": "renters/index.html",
        "arr": "RENTERS_CARRIERS = [",
        "sd": "RENTERS_STATE_DATA = {",
        "fallback": "const RENTERS_FALLBACK =",
    },
    "home": {
        "src": "home/index.html",
        "arr": "HOME_CARRIERS = [",
        "sd": "HOME_STATE_DATA = {",
        "fallback": "const HOME_FALLBACK =",
    },
}


def block(s, start, end="\n];"):
    i = s.index(start)
    j = s.index(end, i)
    return s[i + len(start):j]


def national_carriers(arr_text):
    """National = a carrier object with no `states:` footprint array."""
    names = []
    for chunk in re.split(r'\n  \{', arr_text):
        nm = re.search(r'name:\s*"([^"]+)"', chunk)
        if not nm:
            continue
        if re.search(r'\bstates:\s*\[', chunk):
            continue  # regional footprint carrier — base already state-appropriate
        names.append(nm.group(1).replace("&amp;", "&"))
    return names


def state_avgs(sd_text):
    avgs = {}
    for m in re.finditer(r'"([A-Z]{2})":\s*\{[^}]*?avg:\s*(\d+)', sd_text):
        avgs[m.group(1)] = int(m.group(2))
    return avgs


def build_table(avgs, carriers):
    codes = sorted(avgs, key=lambda c: avgs[c])  # cheapest -> priciest
    n = len(codes)
    pct = {c: i / (n - 1) for i, c in enumerate(codes)}
    table = {}  # state -> {carrier: offset}
    for code in sorted(avgs):
        row = {}
        for car in carriers:
            k = K.get(car)
            if not k:
                continue
            off = round(1 + k * (2 * pct[code] - 1), 2)
            if off == 1.00:
                continue
            row[car] = off
        if row:
            table[code] = row
    return table


def render(table):
    lines = [BEGIN]
    lines.append("// Modeled cost-responsiveness tilt (see gen_product_offsets.py / RATE_METHODOLOGY.md §3).")
    lines.append("// offset = 1 + k*(2*costPercentile-1); agent carriers load high-cost states (k>0),")
    lines.append("// value/direct carriers hold the line (k<0). Modeled, directional. Regionals excluded.")
    lines.append("const STATE_CARRIER_ADJ = {")
    for code in sorted(table):
        pairs = ", ".join('"%s": %s' % (c, ("%g" % v)) for c, v in table[code].items())
        lines.append('  "%s": { %s },' % (code, pairs))
    lines.append("};")
    lines.append(END)
    return "\n".join(lines)


def patch_estimate(s):
    if "STATE_CARRIER_ADJ[stateData" in s:
        return s, False
    anchor = "  var s = carrier.sens;\n  var m = carrier.base;"
    repl = (
        "  var s = carrier.sens;\n"
        "  var stateAdj = (typeof stateData !== 'undefined' && stateData) ? STATE_CARRIER_ADJ[stateData.code] : null;\n"
        "  var stateM = stateAdj ? (stateAdj[carrier.name] || 1.0) : 1.0;\n"
        "  var m = carrier.base * stateM;"
    )
    if anchor not in s:
        raise SystemExit("estimatePremium anchor not found — aborting")
    return s.replace(anchor, repl, 1), True


def process(product):
    cfg = PRODUCTS[product]
    path = ROOT / cfg["src"]
    s = path.read_text(encoding="utf-8")

    carriers = national_carriers(block(s, cfg["arr"]))
    avgs = state_avgs(block(s, cfg["sd"], "\n};"))
    table = build_table(avgs, carriers)
    rendered = render(table)

    # Insert or replace the generated table (idempotent).
    if BEGIN in s:
        i = s.index(BEGIN)
        j = s.index(END, i) + len(END)
        s = s[:i] + rendered + s[j:]
    else:
        # insert right before the FALLBACK const line
        fi = s.index(cfg["fallback"])
        line_start = s.rfind("\n", 0, fi) + 1
        s = s[:line_start] + rendered + "\n\n" + s[line_start:]

    s, patched = patch_estimate(s)
    path.write_text(s, encoding="utf-8")

    cells = sum(len(v) for v in table.values())
    tuned = sorted({c for v in table.values() for c in v})
    print("[%s] %d national carriers tilted across %d states -> %d offset cells%s" % (
        product, len(tuned), len(table), cells,
        "" if patched else " (estimatePremium already patched)"))
    print("        carriers: %s" % ", ".join(tuned))
    return cells


def main():
    targets = sys.argv[1:] or ["renters", "home"]
    total = 0
    for p in targets:
        total += process(p)
    print("Total offset cells written: %d" % total)


if __name__ == "__main__":
    main()
