#!/usr/bin/env python3
"""Directional HOME metro offsets — sub-state granularity for the home tool.

metro_offset = clamp(1 + risk_position(metro) * band(state), 0.72, 1.45).

- band(state): a MODELED half-spread set by the state's home-catastrophe geography (coastal/
  hurricane/wildfire states spread wide; uniform inland states narrow). NOT scaled off the raw
  filing dispersion — filing max/min is the change *redistribution*, which does not equal the level
  *gradient* (e.g. OH carriers redistribute heavily on ~0% filings but OH metros cost about the same).
  The dispersion is used only as CORROBORATION that intra-state spread of this magnitude is real.
- risk_position(metro): modeled home-cost position within its state, -1 (low) .. +1 (high).

Reuses the auto tool's ZIP_PREFIX_METRO (ZIP-prefix -> metro, product-agnostic) so the home tool can
resolve a ZIP to a metro. Directional, labeled as such. True ZIP-level rating needs the carriers'
ZIP->territory maps, which are separate filings (not in the rate jackets) — deferred, see SESSION_NOTES.

Injects HOME_METRO_OFFSET + HOME_METRO_ZIP3 into home/index.html between markers.
"""
import re, json, statistics
from pathlib import Path

ROOT = Path(__file__).parent
HOME = ROOT / "home" / "index.html"
BEGIN = "// ── HOME_METRO_OFFSET (directional sub-state offset) ─ GENERATED by gen_home_metro_offsets.py ──"
END = "// ── END HOME_METRO_OFFSET ──"

# Home-catastrophe half-spread per state (modeled; corroborated by captured filing dispersion for LA/NY/PA/OH).
STATE_BAND = {"LA": 0.20, "NY": 0.20, "TX": 0.20, "CA": 0.15, "PA": 0.11, "OH": 0.07, "IL": 0.10}

# Modeled home-cost position of each metro within its state (-1 low .. +1 high).
METRO_RISK = {
    # LA — Gulf hurricane/flood: New Orleans coastal >> inland Baton Rouge
    "nor": 1.0, "bat": -0.6,
    # NY — coastal/high-value downstate (NYC + Long Island) >> cheap upstate
    "nyc": 1.0, "alb": -0.4, "buf": -0.8, "roc": -0.7, "syr": -0.7,
    # PA — Philadelphia higher, western/Lehigh moderate
    "phl": 0.8, "pit": -0.3, "abe": 0.0,
    # OH — fairly uniform inland; mild lake-effect tilt
    "cle": 0.5, "akr": 0.2, "col": 0.0, "cin": -0.2, "day": -0.2,
    # IL — Chicago metro higher (urban density, hail), downstate lower
    "chi": 0.7,
    # TX — Gulf-coast Houston (hurricane) high; inland hail belt moderate; far-west low
    "hou": 1.0, "dfw": 0.2, "aus": 0.1, "san": 0.0, "elp": -0.8,
    # CA — high-value coastal/Bay high; Central Valley lower
    "sjv": 0.8, "sdg": 0.4, "riv": 0.2, "sac": 0.0, "fre": -0.5, "bak": -0.4,
}


def clamp(v, lo, hi):
    return max(lo, min(hi, v))


def build():
    auto = (ROOT / "index.html").read_text(encoding="utf-8")
    z2m = dict(re.findall(r'"(\d{3})":"([a-z]{3,4})"', auto[auto.index("const ZIP_PREFIX_METRO"):auto.index("const ZIP_PREFIX_METRO") + 40000]))

    # corroboration: max observed by-territory increase per state (from filings)
    F = [r for r in json.load(open(ROOT / "serff_home_filings.json"))["filings"] if r.get("max_pct") is not None]
    corrob = {}
    for r in F:
        corrob[r["state"]] = max(corrob.get(r["state"], 0), r["max_pct"])

    # derive metro->state from ZIP_PREFIX_METRO + the home ZIP3_TO_STATE
    home = HOME.read_text(encoding="utf-8")
    z2s = dict(re.findall(r'"(\d{3})":"([A-Z]{2})"', home[home.index("const ZIP3_TO_STATE"):home.index("const ZIP3_TO_STATE") + 40000]))
    metro_state = {}
    for z3, m in z2m.items():
        st = z2s.get(z3)
        if st:
            metro_state.setdefault(m, {}).setdefault(st, 0)
            metro_state[m][st] += 1
    metro_state = {m: max(d, key=d.get) for m, d in metro_state.items()}

    offsets, zip3 = {}, {}
    for m, rz in METRO_RISK.items():
        st = metro_state.get(m)
        if st not in STATE_BAND:
            continue
        offsets[m] = round(clamp(1 + rz * STATE_BAND[st], 0.72, 1.45), 3)
        for z3, mm in z2m.items():
            if mm == m:
                zip3[z3] = m

    off_lines = "\n".join(f'  "{m}": {v:g},' for m, v in sorted(offsets.items()))
    z3_lines = ",".join(f'"{z}":"{m}"' for z, m in sorted(zip3.items()))

    new_block = (
        BEGIN + "\n"
        "// Modeled metro-level multiplier on the state average: metro = 1 + risk_position × band(state).\n"
        "// The band (spread) is set by each state's home-catastrophe geography; the FILING dispersion\n"
        "// (max/min by territory) corroborates that intra-state spread of this magnitude is real. Directional,\n"
        "// not ZIP-exact. 1.0 when a ZIP resolves to no covered metro (→ state average). ZIP→territory maps\n"
        "// (true ZIP rating) are separate filings, not in the rate jackets — see SESSION_NOTES.\n"
        "const HOME_METRO_OFFSET = {\n" + off_lines + "\n};\n"
        "const HOME_METRO_ZIP3 = {" + z3_lines + "};\n"
        + END)

    i, j = home.index(BEGIN), home.index(END) + len(END)
    HOME.write_text(home[:i] + new_block + home[j:], encoding="utf-8")
    print(f"wrote HOME_METRO_OFFSET — {len(offsets)} metros across {len({metro_state[m] for m in offsets})} states, {len(zip3)} ZIP3 prefixes")
    for st in sorted(STATE_BAND):
        ms = {m: offsets[m] for m in offsets if metro_state.get(m) == st}
        if ms:
            c = f"  (filings show up to +{corrob[st]:g}% by territory)" if st in corrob else "  (modeled; dispersion not yet captured)"
            print(f"  {st} band±{STATE_BAND[st]:g}: {ms}{c}")


if __name__ == "__main__":
    build()
