#!/usr/bin/env python3
"""Filing-derived rate-stability score for the AUTO tool (AUTO_STABILITY_ADJ).

Twin of gen_home_stability.py. The auto tool's per-carrier stability (1-5) is hand-set/marketing-derived
and can contradict the carrier's actual SERFF filings (e.g. American Family scored 4/5 "stable" while
filing +6.8% across GA/SC/TN; Progressive scored 2/5 "volatile" while cutting −2.1% across 6 states).
This recomputes it from serff_filings.json, PEER-RELATIVE and coverage-GATED:

  pressure(c) = mean overall_pct across c's auto filings   (magnitude + direction of recent moves)
  gate        = filed in >= COVERAGE_MIN distinct states AND present in the tool roster, else keep static
  delta       = band of (pressure(c) - peer_median) among gated carriers, with a frequency guard
                (only lower a score if the carrier RAISED in a majority of filings; only raise a score
                 if it held flat/cut in a majority) so one outlier filing can't swing it
  adjusted    = clamp(static + delta, 1, 5)

Measures RECENT rate pressure (~1yr of filings), not lifetime volatility. Injects AUTO_STABILITY_ADJ
into index.html between the GENERATED markers. Read sites go through carrierStab(c). See SESSION_NOTES.
"""
import re, json, statistics
from pathlib import Path

ROOT = Path(__file__).parent
INDEX = ROOT / "index.html"
BEGIN = "// ── AUTO_STABILITY_ADJ (filing-derived rate-stability) ─ GENERATED by gen_auto_stability.py ──"
END = "// ── END AUTO_STABILITY_ADJ ──"
COVERAGE_MIN = 3   # need filings in >= 3 states to override the static score

# filing carrier name -> tool roster name, where they differ
ALIAS = {"Amica": "Amica Mutual"}


def clamp(v, lo, hi):
    return max(lo, min(hi, v))


def band(diff):
    """peer-relative delta from the pressure gap (points above/below peer median)."""
    if diff >= 4.0:  return -2
    if diff >= 1.5:  return -1
    if diff <= -4.0: return 2
    if diff <= -1.5: return 1
    return 0


def static_scores(html):
    """Parse the static per-carrier stability (1-5) from BOTH roster shapes.

    Array roster:  { name: "State Farm", ... stability: 4, ... }
    Dict roster:   "American Family": { ... stability: 4, ... }
    name and stability live on the same line in both. First occurrence wins (the primary
    CARRIERS_STANDARD roster precedes the high-risk and local rosters in the file).
    """
    scores = {}
    for line in html.splitlines():
        sm = re.search(r"stability:\s*(\d)", line)
        if not sm:
            continue
        nm = re.search(r'name:\s*"([^"]+)"', line) or re.match(r'\s*"([^"]+)":\s*\{', line)
        if nm and nm.group(1) not in scores:
            scores[nm.group(1)] = int(sm.group(1))
    return scores


def build():
    html = INDEX.read_text(encoding="utf-8")
    static = static_scores(html)

    filings = [r for r in json.load(open(ROOT / "serff_filings.json"))["filings"]
               if r.get("overall_pct") is not None
               and not r.get("drift_exclude")]  # segment-only/unrepresentative filings must not move stability
    by, states = {}, {}
    for r in filings:
        name = ALIAS.get(r["carrier"], r["carrier"])
        by.setdefault(name, []).append(r["overall_pct"])
        states.setdefault(name, set()).add(r.get("state"))

    # gated carriers = filed in >= COVERAGE_MIN DISTINCT states AND present in the tool roster
    # (distinct-state gate, not filing count — one state's multiple filings isn't cross-state signal)
    gated = {c: v for c, v in by.items() if len(states[c]) >= COVERAGE_MIN and c in static}
    if not gated:
        print("no carriers meet the coverage gate yet"); return
    pressure = {c: statistics.mean(v) for c, v in gated.items()}
    peer_med = statistics.median(pressure.values())

    adj = {}
    rows = []
    for c, v in sorted(gated.items(), key=lambda kv: -pressure[kv[0]]):
        p = pressure[c]
        frac_up = sum(1 for x in v if x > 2) / len(v)
        d = band(p - peer_med)
        # frequency guard: don't lower unless it raised in a majority; don't raise unless it mostly held/cut
        if d < 0 and frac_up < 0.5: d = 0
        if d > 0 and frac_up > 0.4: d = 0
        new = clamp(static[c] + d, 1, 5)
        if new != static[c]:
            adj[c] = new
        rows.append((c, len(states[c]), round(p, 1), round(frac_up, 2), static[c], new))

    obj = "\n".join(f'  "{c}": {adj[c]},' for c in sorted(adj))
    new_block = (BEGIN + "\n"
        "// Overrides the static per-carrier stability score (1-5) with one derived from the carrier's actual\n"
        "// SERFF rate filings, PEER-RELATIVE (raising more than peers → lower; holding flat/cutting → higher)\n"
        "// and GATED on coverage (only carriers filed in >= N states). Absent carriers keep their static score.\n"
        "// Measures RECENT rate pressure (~1yr of filings), not lifetime volatility. Do NOT hand-edit.\n"
        "const AUTO_STABILITY_ADJ = {\n" + obj + ("\n" if obj else "") + "};\n" + END)
    i, j = html.index(BEGIN), html.index(END) + len(END)
    INDEX.write_text(html[:i] + new_block + html[j:], encoding="utf-8")

    print(f"peer median pressure = {peer_med:+.1f}%  |  gate >= {COVERAGE_MIN} states  |  {len(adj)} scores adjusted")
    print("  carrier              states  avg%   %raised  static -> filing")
    for c, n, p, fu, st, nw in rows:
        flag = "  <-- changed" if nw != st else ""
        print(f"  {c:20} {n:4}   {p:+5.1f}%   {fu:>4.0%}     {st}   ->  {nw}{flag}")


if __name__ == "__main__":
    build()
